version: "3.9"
services:
  postgres:
    container_name: spb-dotnet_tpc_postgres_container
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5554:5432"